using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using WSGM.Device.Sdk.Glyphs;

namespace WSGM.Core;

/// <summary>
/// Builds the stylesheet that puts the handheld's own glyphs into Steam.
/// </summary>
/// <remarks>
/// Physical glyphs are a presentation override, and CSS is the whole mechanism. This mirrors what
/// CSSLoader's Handheld Controller Glyphs theme already does correctly on Decky and
/// CSSLoader-Desktop (checked out at <c>_ref/handheld-controller-glyphs</c>): Valve draws each glyph
/// as <c>&lt;img src="/steaminputglyphs/NAME.svg"&gt;</c>, so replacing one is a <c>content:</c>
/// override on that exact <c>src</c>, and hiding a control the device does not have is
/// <c>display: none</c> on the row carrying its glyph. Nothing here patches Steam's own data model.
/// <para>
/// The ownership split is the point of this class and must not blur. <b>WSGM owns the method</b>:
/// the Valve resource names, the selectors, the stylesheet shape, and the injection. <b>The device
/// plugin owns the glyphs</b>: every image emitted here comes from the active plugin's imported
/// profile as an importer-verified data URI. WSGM ships no handheld artwork and maintains no
/// per-device stylesheet — adding either would put WSGM back in the business of tracking hardware it
/// does not own. A plugin supplies artwork and a control map; it never supplies a selector, a URL,
/// or stylesheet text.
/// </para>
/// </remarks>
internal static class SteamGlyphCss
{
    /// <summary>Class marking every style element WSGM owns in a Steam document.</summary>
    /// <remarks>
    /// WSGM removes only nodes carrying this class. CSSLoader marks its own with
    /// <c>css-loader-style</c> and a user running both at once is the normal case, so touching
    /// anything else would break a coexisting tool.
    /// </remarks>
    internal const string OwnedClass = "wsgm-glyph-style";

    /// <summary>Element id of the single stylesheet WSGM installs per document.</summary>
    internal const string ElementId = "wsgm-handheld-glyphs";

    /// <summary>
    /// The Steam logo, drawn as an inline path rather than an image.
    /// </summary>
    /// <remarks>
    /// A handful of Valve glyphs are inline <c>&lt;svg&gt;&lt;path d="…"&gt;</c> instead of an
    /// <c>&lt;img&gt;</c>, so a <c>content:</c> override cannot reach them. The reference theme
    /// matches the container by this exact <c>d</c> attribute, hides the inner <c>svg</c>, and paints
    /// the replacement as a background; WSGM uses the same literal because it is the identity of the
    /// artwork, not a class name.
    /// </remarks>
    internal const string SteamLogoPathData =
        "M21.8011 11.5C22.6531 11.5 23.4391 11.62 24.1591 11.86C24.8791 12.1 25.4851 12.394 25.9771"
        + " 12.742L24.8611 14.722C24.4171 14.41 23.9191 14.158 23.3671 13.966C22.8271 13.774 22.3111"
        + " 13.678 21.8191 13.678C21.2191 13.678 20.7511 13.804 20.4151 14.056C20.0791 14.296 19.9111"
        + " 14.632 19.9111 15.064C19.9111 15.496 20.1091 15.838 20.5051 16.09C20.9011 16.33 21.5071"
        + " 16.594 22.3231 16.882C23.1631 17.182 23.8351 17.458 24.3391 17.71C24.8431 17.962 25.2811"
        + " 18.334 25.6531 18.826C26.0371 19.306 26.2291 19.924 26.2291 20.68C26.2291 21.484 26.0191"
        + " 22.18 25.5991 22.768C25.1911 23.356 24.6151 23.812 23.8711 24.136C23.1271 24.448 22.2751"
        + " 24.604 21.3151 24.604C20.5351 24.604 19.7371 24.502 18.9211 24.298C18.1171 24.082 17.4091"
        + " 23.794 16.7971 23.434L17.6251 21.238C18.2011 21.55 18.8071 21.802 19.4431 21.994C20.0911"
        + " 22.174 20.7271 22.264 21.3511 22.264C22.0351 22.264 22.5451 22.132 22.8811 21.868C23.2291"
        + " 21.604 23.4031 21.256 23.4031 20.824C23.4031 20.392 23.2171 20.056 22.8451 19.816C22.4731"
        + " 19.576 21.9031 19.33 21.1351 19.078C20.2711 18.802 19.5751 18.538 19.0471 18.286C18.5191"
        + " 18.022 18.0631 17.644 17.6791 17.152C17.3071 16.648 17.1211 15.994 17.1211 15.19C17.1211"
        + " 14.446 17.3131 13.798 17.6971 13.246C18.0931 12.682 18.6451 12.25 19.3531 11.95C20.0611"
        + " 11.65 20.8771 11.5 21.8011 11.5Z";

    /// <summary>Container class Steam gives the inline-logo glyph wrapper.</summary>
    /// <remarks>
    /// Generated by Steam's build, so it changes when Steam's CSS modules are rebuilt. It is one of
    /// the two build-coupled selectors here and is verified by the delivery patch's probe before any
    /// rule referencing it is installed; the reference theme carries the same coupling.
    /// </remarks>
    internal const string InlineLogoContainerClass = "_3Jfd85nK4bKoNf_gCSTX6U";

    /// <summary>Row class Steam gives one control line in the configurator lists.</summary>
    /// <remarks>
    /// Build-coupled in the same way as <see cref="InlineLogoContainerClass"/>, and it had already
    /// gone stale: the previous value matched nothing on the reference Claw, so every hide rule
    /// silently applied to zero elements. Read from the live page, where this container holds all
    /// eighteen glyph rows. Only hiding depends on it — the glyph overrides key off Valve's own
    /// asset paths and survive a Steam rebuild — so a future drift costs the absent-control rows
    /// and nothing else.
    /// </remarks>
    internal const string ControlRowClass = "pywHIi8MBtTWNlCbZ_7Qx";

    /// <summary>Container Steam gives one control group in the configurator overview.</summary>
    /// <remarks>
    /// Hiding anchors here rather than on the row: a trackpad is a whole section with its own
    /// heading and four bindings under it, and hiding one row of that left the heading and the rest
    /// behind. The reference theme in <c>_ref/handheld-controller-glyphs</c> uses this same class,
    /// which is one reason to have ported its rules rather than reimplementing them — its selectors
    /// are still accurate against the current client, and were sitting there to be copied.
    /// </remarks>
    internal const string ControlSectionClass = "_1KA4m3xP2X5TGmO81UKYgL";

    /// <summary>Token Steam puts in the id of every binding row, naming the input it belongs to.</summary>
    /// <remarks>
    /// The one build-independent hook in this whole surface, and the reason the reference theme was
    /// worth reading rather than reimplementing: it is Valve's own input enum, spelled out in an
    /// element id — "modeid-7-input-unknown EControllerModeInput ( 55 )-binding-0" — where every
    /// other handle here is a class name that Steam's build rehashes. Unlike the reference, WSGM
    /// does not pair it with a hardcoded number per control, because the row carries the glyph for
    /// its own input and that identifies it just as precisely.
    /// </remarks>
    internal const string BindingRowIdToken = "EControllerModeInput";

    /// <summary>Steam's readable class for one control group in the binding editor.</summary>
    /// <remarks>
    /// Not generated, so unlike <see cref="ControlSectionClass"/> a CSS-module rebuild cannot rename
    /// it. The editor groups controls under this rather than under the overview's hashed class,
    /// which is why hiding worked on the overview and left the trackpads sitting in the editor.
    /// </remarks>
    internal const string DialogSectionClass = "DialogControlsSection";

    /// <summary>
    /// Valve glyph resources that identify a control's row for hiding.
    /// </summary>
    /// <remarks>
    /// Hiding is keyed by the glyph the row displays, which is what makes the rule readable and
    /// survivable: the row element itself has only a generated class, but the image inside it is
    /// addressed by a stable Valve resource name.
    /// </remarks>
    private static readonly (GlyphControlId Control, string ValvePath)[] RowGlyphs =
    [
        // Read off the live configurator on the reference Claw. The previous table named
        // sd_ltrackpad_swipe, shared_m1, shared_l5 and shared_r5 — none of which this build draws —
        // so every hide rule matched nothing and a device with no trackpads and one pair of back
        // buttons still showed both trackpad sections and four back buttons.
        // Both pads, every mode. The binding editor draws glyphs the overview never does — swipe,
        // click and ring — so a list built from one page misses the other: sd_ltrackpad_swipe.svg
        // was dropped as stale when only the overview had been looked at, and it is exactly what
        // the editor uses.
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_up.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_down.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_left.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_right.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_click.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_ring.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_swipe.svg"),
        (GlyphControlId.LeftTrackpad, "/steaminputglyphs/sd_ltrackpad_touch.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_up.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_down.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_left.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_right.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_click.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_ring.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_swipe.svg"),
        (GlyphControlId.RightTrackpad, "/steaminputglyphs/sd_rtrackpad_touch.svg"),
        (GlyphControlId.RearM1, "/steaminputglyphs/sd_l4.svg"),
        (GlyphControlId.RearM2, "/steaminputglyphs/sd_r4.svg"),
        (GlyphControlId.RearLeft2, "/steaminputglyphs/sd_l5.svg"),
        (GlyphControlId.RearRight2, "/steaminputglyphs/sd_r5.svg"),
    ];

    /// <summary>
    /// Builds the complete stylesheet for one resolved profile.
    /// </summary>
    /// <param name="presentation">The active profile's resolved mappings.</param>
    /// <param name="hideAbsentControls">Whether rows for absent controls are hidden.</param>
    /// <returns>The stylesheet, or an empty string when the profile supplies nothing to apply.</returns>
    internal static string Build(
        SteamInputGlyphPresentation presentation,
        bool hideAbsentControls)
    {
        ArgumentNullException.ThrowIfNull(presentation);
        StringBuilder css = new();
        css.Append("/* WSGM handheld glyphs: profile ")
            .Append(Comment(presentation.ProfileId))
            .Append(" revision ")
            .Append(presentation.Revision.ToString(CultureInfo.InvariantCulture))
            .Append(". Generated; do not edit in place. */\n");

        int rules = AppendImageOverrides(css, presentation);
        rules += AppendInlineLogoOverride(css, presentation);
        rules += AppendControllerImages(css, presentation);
        if (hideAbsentControls)
        {
            rules += AppendAbsentControlHiding(css, presentation);
        }

        return rules == 0 ? string.Empty : css.ToString();
    }

    private static int AppendImageOverrides(
        StringBuilder css,
        SteamInputGlyphPresentation presentation)
    {
        // Several Valve resources map onto one physical control, so the selectors are grouped by
        // asset. That keeps the stylesheet small and, more usefully, makes an accidental duplicate
        // mapping visible as a repeated asset rather than as silently competing rules.
        var byAsset = presentation.StableResources
            .GroupBy(mapping => mapping.Asset.DataUri, StringComparer.Ordinal)
            .ToArray();
        foreach (var group in byAsset)
        {
            string selector = string.Join(
                ",\n",
                group
                    .Select(mapping => mapping.ValvePath)
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(path => path, StringComparer.Ordinal)
                    .Select(path => $"img[src=\"{Attribute(path)}\"]"));
            css.Append(selector)
                .Append(" {\n  content: url(\"")
                .Append(Url(group.Key))
                .Append("\");\n  transform: scale(1);\n}\n");
        }

        return byAsset.Length;
    }

    private static int AppendInlineLogoOverride(
        StringBuilder css,
        SteamInputGlyphPresentation presentation)
    {
        SteamInputGlyphResourceMapping? guide = presentation.StableResources
            .FirstOrDefault(mapping => mapping.Control is GlyphControlId.Guide);
        if (guide is null)
        {
            return 0;
        }

        string container = "." + InlineLogoContainerClass;
        string path = $"svg path[d=\"{Attribute(SteamLogoPathData)}\"]";
        // The inner svg is hidden rather than removed, and the replacement is painted on the
        // container: the svg is Steam's own node, and WSGM owns no DOM here, only style.
        //
        // visibility, not display. The container is a flex box whose only child is that svg, so
        // display:none collapsed it to 0x0 and the background had no area to paint into — measured
        // exactly that on the reference Claw, where the footer's Menu hint showed no glyph at all
        // while both halves of this override were demonstrably applied. Hiding it this way keeps
        // the box, and the container stays 61x22.
        css.Append(container)
            .Append(" svg:has(> [d=\"")
            .Append(Attribute(SteamLogoPathData))
            .Append("\"]) {\n  visibility: hidden;\n}\n")
            .Append(container)
            .Append(":has(")
            .Append(path)
            .Append(") {\n  background: url(\"")
            .Append(Url(guide.Asset.DataUri))
            .Append("\") center no-repeat;\n  background-size: contain;\n}\n");
        return 1;
    }

    private static int AppendControllerImages(
        StringBuilder css,
        SteamInputGlyphPresentation presentation)
    {
        if (presentation.ControllerImages.Count == 0)
        {
            return 0;
        }

        // Published as custom properties rather than as selectors, which is how the reference theme
        // separates the device-specific half from the shared rules: the device supplies artwork, and
        // whatever renders the controller diagram reads these.
        css.Append(":root {\n");
        foreach (SteamInputGlyphControllerImageMapping image in presentation.ControllerImages
            .OrderBy(image => image.Slot, StringComparer.Ordinal))
        {
            css.Append("  --wsgm-controller-")
                .Append(Identifier(image.Slot))
                .Append("-image: url(\"")
                .Append(Url(image.Asset.DataUri))
                .Append("\");\n");
        }

        css.Append("}\n");
        return presentation.ControllerImages.Count;
    }

    private static int AppendAbsentControlHiding(
        StringBuilder css,
        SteamInputGlyphPresentation presentation)
    {
        HashSet<GlyphControlId> absent = [.. presentation.AbsentControls];

        // Anchored on the section container and matched by the Valve glyph anywhere inside it, so a
        // control the device does not have takes its heading and its bindings with it. The previous
        // form required the glyph to be an immediate grandchild of a row, which described neither
        // the trackpad sections nor the back-button rows as Steam actually builds them.
        string[] selectors = RowGlyphs
            .Where(row => absent.Contains(row.Control))
            .SelectMany(row => new[]
            {
                $".{ControlSectionClass}:has(img[src=\"{Attribute(row.ValvePath)}\"])",

                // And the control's binding rows, which live outside that section. Steam gives each
                // one an id containing its own input enum — "EControllerModeInput ( 55 )-binding-0"
                // — and, measured on the reference Claw, the row also carries the glyph for that
                // input. Matching the stable token together with the glyph means WSGM never needs
                // the enum's numbering: the reference theme hardcodes one number per control, which
                // is a table someone has to keep, and this is the same hook without it.
                $"[id*=\"{BindingRowIdToken}\"]:has(img[src=\"{Attribute(row.ValvePath)}\"])",

                // And the binding editor's own grouping, which uses readable class names rather
                // than generated ones — the same family as Panel and Focusable. Worth preferring
                // wherever Steam offers it: this is the only anchor here that a CSS-module rebuild
                // cannot rename.
                $".{DialogSectionClass}:has(img[src=\"{Attribute(row.ValvePath)}\"])",
            })
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (selectors.Length == 0)
        {
            return 0;
        }

        // Both the row and its contents: Steam sizes some list rows from their children, so hiding
        // only the wrapper can leave a gap where the control used to be.
        css.Append(string.Join(",\n", selectors.SelectMany(selector => new[] { selector, selector + " *" })))
            .Append(" {\n  display: none;\n}\n");
        return selectors.Length;
    }

    /// <summary>Escapes a value for use inside a double-quoted CSS attribute selector.</summary>
    /// <param name="value">The raw value.</param>
    /// <returns>The escaped value.</returns>
    internal static string Attribute(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    /// <summary>
    /// Rejects anything that could break out of a CSS <c>url("…")</c> token.
    /// </summary>
    /// <param name="value">The data URI to emit.</param>
    /// <returns>The value, unchanged when it is safe to emit.</returns>
    /// <exception cref="ArgumentException">The value is not a bounded data URI.</exception>
    /// <remarks>The importer supplies bounded data URIs; any other value violates that contract.</remarks>
    internal static string Url(string value)
    {
        if (!value.StartsWith("data:", StringComparison.Ordinal)
            || value.AsSpan().ContainsAny("\"'()\\\r\n"))
        {
            throw new ArgumentException(
                "Only a bounded data URI may be emitted into a glyph stylesheet.",
                nameof(value));
        }

        return value;
    }

    private static string Identifier(string value) =>
        new([.. value.Where(character => char.IsAsciiLetterOrDigit(character) || character == '-')]);

    private static string Comment(string value) =>
        new([.. value.Where(character =>
            char.IsAsciiLetterOrDigit(character) || character is '-' or '.' or '_')]);
}
